### ISSUE TITLE
Arrange transportation while in DC, 10/7

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/fec-efiling#10]

**Comment by LindsayYoung** [comment]
I think the lowest risk might be to take the silver line and do a car service to and from. I am worried about traffic if we tried to do a car the whole way.

https://www.google.com/maps/dir/1800+F+St+NW,+Washington,+DC/Tysons+Corner+Center,+1961+Chain+Bridge+Rd,+Tysons,+VA+22102/@38.8991858,-77.2716505,11z/am=t/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x89b7b7bb260a2bef:0x9362577f128d1602!2m2!1d-77.0425648!2d38.8969637!1m5!1m1!1s0x89b64ae89541ace1:0x22f6262ba3525df2!2m2!1d-77.2222368!2d38.917623!3e3?hl=en
