### ISSUE TITLE
scope django upgrade

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-efiling#48]
Since this will be backwards incompatible we will want to reachout to the efiling team

**Comment by LindsayYoung** [comment]
It looks like the latest patch we are running is actually OK, in that case we might want to write out the version explicitly so the gymnasium alert turns off, though, I am not sure why it is not interpreting the current range as correct.

**Comment by AmyKort** [comment]
can we close this?

**Comment by AmyKort** [comment]
ping

**Comment by anthonygarvan** [comment]
yes thanks @AmyKort !
